
project_id = "cyuyrpwtkljfiqwgasmn"

[auth.redirect]
site_url = "https://www.pdk12.dk"
redirect_urls = ["https://www.pdk12.dk/password-reset", "https://www.pdk12.dk/reset-password"]

[functions.admin-create-user]
verify_jwt = true
