
project_id = "cyuyrpwtkljfiqwgasmn"

[auth.redirect]
site_url = "https://www.pdk12.dk"
redirect_urls = ["https://www.pdk12.dk/login", "https://www.pdk12.dk/password-reset", "https://www.pdk12.dk/reset-password"]

[functions.admin-create-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-user-role]
verify_jwt = true

[functions.admin-user-delete]
verify_jwt = true
