
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyuyrpwtkljfiqwgasmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5dXlycHd0a2xqZmlxd2dhc21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3Njg5ODEsImV4cCI6MjA2MjM0NDk4MX0.j6NYT5jwYaYhZYVsRqW20T6_I9WkcqSmZ-rHyA78k5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'supabase.auth.token',
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    global: {
      headers: {
        'X-Client-Info': 'supabase-js/2.43.1'
      },
    },
  }
);

// Add global error handler for Supabase operations
const handleSupabaseError = (error: any) => {
  if (error) {
    console.error('Supabase operation failed:', error.message || error);
    
    // Add specific error handling based on error types
    if (error.code === 'PGRST301') {
      console.error('Row-level security policy error');
    } else if (error.code === 'P0001') {
      console.error('Database constraint violation');
    }
  }
};

// Create enhanced methods with error handling
export const enhancedSupabase = {
  ...supabase,
  safeQuery: async (queryFn: () => Promise<any>) => {
    try {
      const result = await queryFn();
      if (result.error) {
        handleSupabaseError(result.error);
      }
      return result;
    } catch (err) {
      handleSupabaseError(err);
      return { data: null, error: err };
    }
  }
};
