// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjjworqqbbrbtfvtkqyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqandvcnFxYmJyYnRmdnRrcXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODM2NzUsImV4cCI6MjA2MjI1OTY3NX0.2AH2qjFrBL7vjdt3ZndC13rYLVI0ajPZSaZyb-baA_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);