
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyuyrpwtkljfiqwgasmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5dXlycHd0a2xqZmlxd2dhc21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3Njg5ODEsImV4cCI6MjA2MjM0NDk4MX0.j6NYT5jwYaYhZYVsRqW20T6_I9WkcqSmZ-rHyA78k5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true, // This helps with extracting tokens from URLs
      storageKey: 'supabase.auth.token',
      flowType: 'pkce', // Use PKCE flow for more security
      debug: import.meta.env.DEV, // Enable debug mode in development
      storage: {
        getItem: (key) => {
          try {
            const value = localStorage.getItem(key);
            return value;
          } catch (error) {
            console.error('Error accessing localStorage:', error);
            return null;
          }
        },
        setItem: (key, value) => {
          try {
            localStorage.setItem(key, value);
          } catch (error) {
            console.error('Error writing to localStorage:', error);
          }
        },
        removeItem: (key) => {
          try {
            localStorage.removeItem(key);
          } catch (error) {
            console.error('Error removing from localStorage:', error);
          }
        },
      },
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    global: {
      headers: {
        'X-Client-Info': 'supabase-js/2.43.1'
      },
    },
  }
);

// Add global error handler for Supabase operations
export const handleSupabaseError = (error: any, context?: string) => {
  if (error) {
    const errorContext = context ? `[${context}] ` : '';
    console.error(`${errorContext}Supabase operation failed:`, error.message || error);
    
    // Add specific error handling based on error types
    if (error.code === 'PGRST301') {
      console.error('Row-level security policy error');
    } else if (error.code === 'P0001') {
      console.error('Database constraint violation');
    } else if (error.code === 'refresh_token_not_found') {
      console.error('Authentication token issue: Refresh token not found');
    } else if (error.code === 'invalid_token') {
      console.error('Authentication token issue: Invalid token');
    } else if (error.code === 'expired_token') {
      console.error('Authentication token issue: Token has expired');
    }

    // Return a standardized error format
    return {
      message: error.message || 'An unexpected error occurred',
      code: error.code || 'unknown_error',
      status: error.status || 500
    };
  }
  return null;
};

// Create enhanced methods with improved error handling
export const enhancedSupabase = {
  ...supabase,
  safeQuery: async (queryFn: () => Promise<any>, context?: string) => {
    try {
      const result = await queryFn();
      if (result.error) {
        handleSupabaseError(result.error, context);
      }
      return result;
    } catch (err) {
      handleSupabaseError(err, context);
      return { data: null, error: err };
    }
  }
};

// Helper function to verify and refresh auth tokens
export const ensureValidSession = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Session validation error:', error);
      return false;
    }
    
    if (!data.session) {
      console.log('No active session found');
      return false;
    }
    
    // Check if token is close to expiry (within 5 minutes)
    const expiresAt = data.session.expires_at;
    if (expiresAt) {
      const expiryTime = expiresAt * 1000; // Convert to milliseconds
      const currentTime = Date.now();
      const timeToExpiry = expiryTime - currentTime;
      
      // If token expires in less than 5 minutes, refresh it
      if (timeToExpiry < 300000 && timeToExpiry > 0) {
        console.log('Token expires soon, refreshing...');
        const { error: refreshError } = await supabase.auth.refreshSession();
        if (refreshError) {
          console.error('Failed to refresh token:', refreshError);
          return false;
        }
      }
    }
    
    return true;
  } catch (error) {
    console.error('Error ensuring valid session:', error);
    return false;
  }
};
